app/protected/models/Listadocables.php
<?php

/**
 * This is the model class for table "listadocables".
 *
 * The followings are the available columns in table 'listadocables':
 * @property integer $id
 * @property string $tipo
 * @property integer $componente_id
 * @property integer $proveedor_id
 * @property string $cod_setecel
 * @property integer $materia_prima_fk
 * @property string $Descripcion
 * @property string $Unidad_Medida
 * @property integer $stock
 * @property string $nombre
 */
class Listadocables extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'listadocables';
	}

	public function primaryKey()
	{
		return 'id';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('cod_setecel, Descripcion, Unidad_Medida, stock, nombre', 'required'),
			array('id, componente_id, proveedor_id, materia_prima_fk, stock', 'numerical', 'integerOnly'=>true),
			array('tipo', 'length', 'max'=>5),
			array('cod_setecel, Unidad_Medida', 'length', 'max'=>11),
			array('Descripcion', 'length', 'max'=>15),
			array('nombre', 'length', 'max'=>100),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, tipo, componente_id, proveedor_id, cod_setecel, materia_prima_fk, Descripcion, Unidad_Medida, stock, nombre', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'proveedor_fk' => array(self::BELONGS_TO, 'Proveedor', 'proveedor_id'),
			'materiaPrimaFk' => array(self::BELONGS_TO, 'MateriaPrima', 'materia_prima_fk'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'tipo' => 'Tipo',
			'componente_id' => 'Componente',
			'proveedor_id' => 'Proveedor',
			'cod_setecel' => 'Cod Setecel',
			'materia_prima_fk' => 'Materia Prima Fk',
			'Descripcion' => 'Descripcion',
			'Unidad_Medida' => 'Unidad Medida',
			'stock' => 'Stock',
			'nombre' => 'Nombre',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('tipo',$this->tipo,true);
		$criteria->compare('componente_id',$this->componente_id);
		$criteria->compare('proveedor_id',$this->proveedor_id);
		$criteria->compare('cod_setecel',$this->cod_setecel,true);
		$criteria->compare('materia_prima_fk',$this->materia_prima_fk);
		$criteria->compare('Descripcion',$this->Descripcion,true);
		$criteria->compare('Unidad_Medida',$this->Unidad_Medida,true);
		$criteria->compare('stock',$this->stock);
		$criteria->compare('nombre',$this->nombre,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Listadocables the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

app/protected/controllers/CableController.php
<?php

class CableController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(array('CrugeAccessControlFilter'));
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{

		$model = $this->loadModel($id);
		if ($model->materia_fk->Inactivo == 0) {
			$model->materia_fk->Inactivo = "No";
		}else{
			$model->materia_fk->Inactivo = "Si";
		}

		$this->render('view',array(
			'model'=>$model,
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Cable;

		if (isset($_GET['id'])) {
			$model->materia_prima_fk = $_GET['id'];
		}else{
			$this->redirect(array('materiaPrima/create'));
		}

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Cable']))
		{
			$model->attributes=$_POST['Cable'];
			if($model->save())
				$this->redirect(array('stock/crearcable','id'=>$model->materia_prima_fk));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=new Cable;
		$model=$model->findByAttributes(array('materia_prima_fk'=>$id));
		//$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Cable']))
		{
			$model->attributes=$_POST['Cable'];
			if($model->save())
				$this->redirect(array('stock/update','id'=>$model->materia_prima_fk));


				//$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->redirect(array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Cable('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Cable']))
			$model->attributes=$_GET['Cable'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Cable the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Cable::model()->with('materia_fk')->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Cable $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='cable-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/controllers/ListadocablesController.php
<?php

class ListadocablesController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(array('CrugeAccessControlFilter'));
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Listadocables;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Listadocables']))
		{
			$model->attributes=$_POST['Listadocables'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Listadocables']))
		{
			$model->attributes=$_POST['Listadocables'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$this->redirect(array('admin'));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Listadocables('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Listadocables']))
			$model->attributes=$_GET['Listadocables'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Listadocables the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Listadocables::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Listadocables $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='listadocables-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

app/protected/views/listadocables/_search.php
<?php
/* @var $this ListadocablesController */
/* @var $model Listadocables */
/* @var $form CActiveForm */
?>

<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'tipo', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'tipo',array('size'=>5,'maxlength'=>5)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'componente_id', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'componente_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'proveedor_id', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'proveedor_id'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'cod_setecel', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'cod_setecel',array('size'=>30,'maxlength'=>30)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'materia_prima_fk', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'materia_prima_fk'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Descripcion', array('class'=>'col-sm-2 col-form-label')); ?>
		<?php echo $form->textField($model,'Descripcion',array('size'=>15,'maxlength'=>15)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'Unidad_Medida'); ?>
		<?php echo $form->textField($model,'Unidad_Medida',array('size'=>11,'maxlength'=>11)); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'stock'); ?>
		<?php echo $form->textField($model,'stock'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'nombre'); ?>
		<?php echo $form->textField($model,'nombre',array('size'=>60,'maxlength'=>100)); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Search'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

app/protected/views/listadocables/_view.php
<?php
/* @var $this ListadocablesController */
/* @var $data Listadocables */
?>

<div class="view">

	<b><?php echo CHtml::encode($data->getAttributeLabel('id')); ?>:</b>
	<?php echo CHtml::link(CHtml::encode($data->id), array('view', 'id'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('tipo')); ?>:</b>
	<?php echo CHtml::encode($data->tipo); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('componente_id')); ?>:</b>
	<?php echo CHtml::encode($data->componente_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('proveedor_id')); ?>:</b>
	<?php echo CHtml::encode($data->proveedor_id); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('cod_setecel')); ?>:</b>
	<?php echo CHtml::encode($data->cod_setecel); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('materia_prima_fk')); ?>:</b>
	<?php echo CHtml::encode($data->materia_prima_fk); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('Descripcion')); ?>:</b>
	<?php echo CHtml::encode($data->Descripcion); ?>
	<br />

	<?php /*
	<b><?php echo CHtml::encode($data->getAttributeLabel('Unidad_Medida')); ?>:</b>
	<?php echo CHtml::encode($data->Unidad_Medida); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('stock')); ?>:</b>
	<?php echo CHtml::encode($data->stock); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('nombre')); ?>:</b>
	<?php echo CHtml::encode($data->nombre); ?>
	<br />

	*/ ?>

</div>

app/protected/views/listadocables/admin.php
<?php
/* @var $this ListadocablesController */
/* @var $model Listadocables */

$this->breadcrumbs=array(
	'Listadocables'=>array('index'),
	'Manage',
);

$this->menu=array(
	array('label'=>'List Listadocables', 'url'=>array('index')),
	array('label'=>'Create Listadocables', 'url'=>array('create')),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#listadocables-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1>Administrar Listadocables</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'htmlOptions' => array('class' => 'tables'),
	'itemsCssClass' => 'table-class',
	'id'=>'listadocables-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		'id',
		'tipo',
		'componente_id',
		'proveedor_id',
		'cod_setecel',
		'materia_prima_fk',
		/*
		'Descripcion',
		'Unidad_Medida',
		'stock',
		'nombre',
		*/
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

app/protected/views/listadocables/cablestabs.php
<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'listadocables-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id',
		'tipo',
		//'componente_id',
		array(
			'name'=>'proveedor_id',
			'header'=>'Proveedor',
			'value'=>'$data->getRelated(\'proveedor_fk\')->nombre', // ESTO TRAE EL DATO DE OTRA TABLA RELACIONADA
		),
		'cod_setecel',
		'Unidad_Medida',
		'stock',
		//'materia_prima_fk',
		/*
		'Descripcion',
		'Unidad_Medida',
		'stock',
		'nombre',
		*/
		array(
			'class'=>'CButtonColumn',
			'template'=>'{view}{update}',
			'buttons'=>array
			(
				'view' => array
				(
					'label'=>'Ver mas',
					'url'=>'Yii::app()->createUrl("cable/view", array("id"=>$data->componente_id))',
				),
				'update' => array
				(
					'label'=>'Ver mas',
					'url'=>'Yii::app()->createUrl("materiaPrima/update", array("id"=>$data->id))',
				),
			),
		),
	),
)); ?>

app/protected/views/listadocables/cablestabsbuscar.php
<?php 

$data = CHtml::listData(Cable::model()->findAll(), 'id', 'cod_setecel');

echo $form->listBox($model,'cod_setecel',$data,array('multiple'=>'multiple','size'=>'5', 'class'=>'form-control'));

/*

				$this->widget('CTabView', array(
				    'tabs'=>array(
				        'tabcable'=>array(
				            'title'=>'Cables',
				            'view'=>'../listadocables/cablestabsbuscar',
				            'data'=>array('model'=>$cables, 'form'=>$form),
				        ),
				        'tabcomponente'=>array(
				            'title'=>'Componentes',
				            'view'=>'../listadocomponentes/componentestabsbuscar',
				            'data'=>array('model'=>$componentes, 'form'=>$form),
				        ),
				    ),
				    'htmlOptions'=>array(
				            'style'=>'width:500px;',
				            ),
				));
*/

?>

app/protected/views/listadocables/index.php
<?php
/* @var $this ListadocablesController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Listadocables',
);

$this->menu=array(
	array('label'=>'Create Listadocables', 'url'=>array('create')),
	array('label'=>'Manage Listadocables', 'url'=>array('admin')),
);
?>

<h1>Listadocables</h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); ?>

app/protected/views/listadocables/view.php
<?php
/* @var $this ListadocablesController */
/* @var $model Listadocables */

$this->breadcrumbs=array(
	'Listadocables'=>array('index'),
	$model->id,
);

$this->menu=array(
	array('label'=>'List Listadocables', 'url'=>array('index')),
	array('label'=>'Create Listadocables', 'url'=>array('create')),
	array('label'=>'Update Listadocables', 'url'=>array('update', 'id'=>$model->id)),
	array('label'=>'Delete Listadocables', 'url'=>'#', 'linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>'Manage Listadocables', 'url'=>array('admin')),
);
?>

<h1>View Listadocables #<?php echo $model->id; ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		'id',
		'tipo',
		'componente_id',
		'proveedor_id',
		'cod_setecel',
		'materia_prima_fk',
		'Descripcion',
		'Unidad_Medida',
		'stock',
		'nombre',
	),
)); ?>